spring:
  cloud:
    stream:
      binders:
        kafka1:
          type: kafka
          defaultCandidate: true
      bindings:
        output:
          content-type: application/json
        input:
          content-type: application/json
logging:
  path: '/Users/ToVn/elk/logstash/spring-boot/'
  file:
    max-history: 10
  level: TRACE
server:
  port: 0
